---
Limpeza e Tratamento de Dados - R
---
```{r}
#Importa dados, string vazio como NA, string como fatores
dados = read.csv("Churn.csv", sep = ";", na.strings = "", stringsAsFactors = T)
head(dados)
summary(dados)
```
Colunas
```{r}
#Dar nomes corretos as colunas
colnames(dados) = c("Id", "Score", "Estado", "Genero", "Idade", "Patrimonio", "Saldo", "Produtos", "TemCartCredito", "Ativo", "Salario", "Saiu")
head(dados)
```
Explorar Dados, colunas categóricas
```{r}
#Estados
counts = table(dados$Estado)
barplot(counts, main="Estados", xlab="Estados")
#Gênero
counts = table(dados$Genero)
barplot(counts, main="Gêneros", xlab="Gêneros")
```
Explorar, colunas numéricas
```{r}
#Score
summary(dados$Score)
boxplot(dados$Score)
hist(dados$Score)
```
```{r}
#Idade
summary(dados$Idade)
boxplot(dados$Idade)
hist(dados$Idade)
```
```{r}
#Saldo
summary(dados$Saldo)
boxplot(dados$Saldo)
hist(dados$Saldo)
```
```{r}
#Salário
summary(dados$Salario)
boxplot(dados$Salario)
boxplot(dados$Salario, outline = F)
```
Valores Faltantes - NAs
```{r}
#valores faltantes -NAs
dados[!complete.cases(dados),]
```
Tratando Salários
```{r}
#Tratar salários
summary(dados$Salario)
#ver mediana
median(dados$Salario,na.rm = T)
#atribuir mediana a NAs
dados[is.na(dados$Salario),]$Salario = median(dados$Salario,na.rm = T)
#buscar NAs em salario para checar
dados[!complete.cases(dados$Salario),]
```
Falta de Padronização em Gênero
```{r}
#Ver valores
unique(dados$Genero)
summary(dados$Genero)
#Transformar F e Fem em Feminino - "", M em Masculino (Moda)
dados[is.na(dados$Genero) | dados$Genero =="M",]$Genero = "Masculino"
dados[dados$Genero == "F" | dados$Genero == "Fem",]$Genero = "Feminino"
#Ver resultado
summary(dados$Genero)
#Remover levels não utilizados
dados$Genero = factor(dados$Genero)
#Visualizar novamente
summary(dados$Genero)
```
Idades fora do Domínio
```{r}
summary(dados$Idade)
#Fora do Dominio, númerico - ver idades anormais
dados[dados$Idade<0 | dados$Idade>110 ,]$Idade
#Não temos idade NAs
dados[is.na(dados$Idade),]
#opção, preencher com mediana
median(dados$Idade)
#Substituição
dados[dados$Idade<0 | dados$Idade>110 ,]$Idade = median(dados$Idade)
#Buscamos novamente idades anormais
dados[dados$Idade<0 | dados$Idade>110 ,]
summary(dados$Idade)
```
Dados Duplicados
```{r}
#Buscar duplicados pelo ID
x = dados[duplicated(dados$Id),]
x
#Verificamos que o ID 81 está duplicado - vamos excluir pelo índice 82
dados = dados[-c(82),]
#Buscamos a linha que estava duplicada
dados[dados$Id == x$Id ,]
#Verificamos Novamente duplicados
x= dados[duplicated(dados$Id) ,]
x
```
Estado fora do Domínio
```{r}
#Fora do Domínio - Categorico
unique(dados$Estado)
summary(dados$Estado)
#Preencher com a moda, RS
dados[!dados$Estado %in% c("RS", "SC", "PR"),]$Estado = "RS"
summary(dados$Estado)
#Removemos fatores não usados
dados$Estado = factor(dados$Estado)
#Visualizar Novamente
summary(dados$Estado)
```
Outliers
```{r}
#Outliers, criando um parâmetro com desvio padrão
desv = sd(dados$Salario, na.rm = T)
desv
dados[dados$Salario >= 2*desv ,]$Salario
#Outra forma, resultado semelhante, mas sem os NAs
boxplot(dados$Salario)
boxplot(dados$Salario, outline = F)
x = boxplot(dados$Salario)$out
x
#Atualizamos todos para Mediana
median(dados$Salario)
dados[dados$Salario >= 2*desv ,]$Salario = median(dados$Salario)
#Checamos se sairam os outliers
dados[dados$Salario >= 2*desv ,]$Salario
```

